# Deploy a Producción
name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Install dependencies
      #   run: |
      #     if [ ! -d vendor ]; then
      #       composer install --no-interaction --prefer-dist --optimize-autoloader
      #     fi

      - name: Deploy to Hostinger
        run: |
          ssh -p 65002 -o ConnectTimeout=30 -o StrictHostKeyChecking=no u775018289@213.130.145.55 << 'EOF'
            cd domains/panificadorabutron-panel.com/public_html/butron &&
            git pull origin main &&
            php artisan cache:clear &&
            php artisan config:cache
          EOF
